name: Maintain bun.lockb

on:
  push:
    branches: [main]
    paths:
      - 'package-lock.json'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  run:
    name: bun install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@d3603274aca5625baad52ec06108517a089cdd00 # v1
        with:
          bun-version: latest
      - run: bun install
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ secrets.ECOSPARK_APP_ID }}
          private-key: ${{ secrets.ECOSPARK_APP_PRIVATE_KEY }}
      - uses: peter-evans/create-pull-request@70a41aba780001da0a30141984ae2a0c95d8704e # v6
        with:
          body: I ran `bun install` 🧑‍💻
          branch: actions/maintain-bun-lock
          commit-message: 'chore(bun): update bun lockfile'
          labels: 🤖 bot
          title: 'chore(bun): update bun lockfile'
          token: ${{ steps.app-token.outputs.token }}
